apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskExpenseTracker

spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskExpenseTracker
  template:
    metadata:
      labels:
        app: flaskExpenseTracker

    spec:
      containers:
        - name: j007
          image: docker.io/jaihindh07/expensetracker:latest
          ports:
            - containerPort: 5000
              protocol: TCP